version: '3.7'
services:
  microblink-license-usage-logs-uploader:
    image: docker.microblink.com/license-usage-logs-uploader:0.4.1
    environment:
      - LICENSE_USAGE_LOGS_HEADERS_AUTHORIZATION=NGJlNmEyMzItZWRmOC00ZGI2LTlmNWUtMjAwNmJlYWRiMmM1OlR2Y25oeW95a2JTa1ZNTF9OUGVqZFhXVTN6diNIbDYweW9JMlN4LW8=
      - CRON_SCHEDULE=*/10 * * * * *

    ports:
      - 8085:8080
    volumes:
      - /var/microblink/blinkid-verify-server/app/srv/blinkid-verify-license-usage-logs:/blinkid-verify-license-usage-logs
      - /var/microblink/blinkid-verify-server/app/srv/facetec-license-usage-logs:/facetec-license-usage-logs
